In [ ]:
import pandas as pd

Gene selection criterion:

_log2FoldChange: the direction and intensity on a log2 scale: +2 means 4x more expression (here, in hypoxia), -3 means 8x less. It is an estimate with uncertainty that is captured by the lfcSE column (standard error). 

Example: a gene with log2FC = 4.9 but lfcSE = 1.3 is less trustworthy than log2FC = 2.7 and lfcSE = 0.26

_padj: probability of observing counts this extreme assuming the gene is not DE

baseMean: the mean of the normalized counts for that gene, averaged accross all samples, both conditions (O2 and no O2 pooled). Tells us how much the gene is expressed overall, i.e how much data underlies the statistics. 

    Low baseMean : the fold change is computed from a handfull of reads, so the estimate is noisy. 

    High baseMean: the gene is abundantly expressed and the fold change is solid. Also an abundant transcript should be easier to validate by RT-qPCR or Northern blot

In [ ]:
hypoxia_data = pd.read_csv("rnaseq_hypoxia.csv", sep=";", index_col=0)
normoxia_data = pd.read_csv("rnaseq_normoxia.csv", sep=";", index_col=0)
overview_data = pd.read_csv("01_complete_gene_ranking.csv", sep=",", index_col=0)

In [3]:
#filter choices
basemean = 200
fold_change_hypoxia = 2.5
fold_change_normoxia = -2.5
p_adj =  1e-6

In [ ]:
normoxia_query = "baseMean >= @basemean & log2FoldChange <= @fold_change_normoxia & padj <= @p_adj"
hypoxia_query = "baseMean >= @basemean & log2FoldChange >= @fold_change_hypoxia & padj <= @p_adj"

In [ ]:
print(len(overview_data.query(hypoxia_query)))
print(overview_data.query(hypoxia_query))

26
                 baseMean  log2FoldChange  shrunkLFC     lfcSE          padj  \
gene
CPAR2_402940  7717.697743        2.953720   2.920630  0.227468  6.601696e-36
CPAR2_603610  7156.497733        3.539613   3.520083  0.218040  2.404149e-56
CPAR2_802240   408.763107        3.522685   3.504361  0.183325  5.293314e-79
CPAR2_100710   385.891356        3.041895   2.943354  0.394597  7.729328e-13
CPAR2_201490  1319.671380        2.852737   2.801407  0.277791  1.600267e-22
CPAR2_405010  9437.133347        2.526734   2.488266  0.243220  5.046353e-23
CPAR2_500850  6775.786781        3.000224   2.964103  0.239512  2.063846e-33
CPAR2_401300  2098.278340        3.385799   3.363428  0.199031  7.818586e-62
CPAR2_108000   870.276156        2.999223   2.978282  0.182172  6.449306e-58
CPAR2_109500   800.730446        2.527252   2.489833  0.225288  9.637753e-27
CPAR2_403180  6939.334408        2.578104   2.455158  0.404939  4.695487e-09
CPAR2_203450  3371.879372        6.099724   5.740083  1.045131  9.675807e-08
CPAR2_212210  2921.963451        2.838375   2.777329  0.301261  5.707550e-19
CPAR2_302890   567.068475        2.512929   2.445687  0.299746  4.183957e-15
CPAR2_804750   268.603407        2.620834   2.528164  0.355712  7.835896e-12
CPAR2_503040  1851.914845        2.763683   2.688364  0.328954  3.644730e-15
CPAR2_400770   355.303773        2.795683   2.698001  0.375196  4.531878e-12
CPAR2_600270   218.271357        3.636162   3.549053  0.402685  1.776368e-17
CPAR2_503690  1418.046930        2.702862   2.638229  0.302573  4.067485e-17
CPAR2_800230  1007.442908        2.682581   2.561157  0.412452  2.028312e-09
CPAR2_100100   375.406737        3.272075   3.226322  0.279941  4.692675e-29
CPAR2_205500   250.903803        2.815862   2.722832  0.369206  1.364658e-12
CPAR2_807040   468.906335        2.887651   2.818883  0.318834  1.411357e-17
CPAR2_105270   658.202531        2.915187   2.819140  0.379652  9.591773e-13
CPAR2_807600   336.574079        2.603500   2.477405  0.414091  7.445362e-09
CPAR2_301390   267.815009        2.580037   2.486575  0.352782  1.124189e-11

              effectTestPadj        svalue   maxCook  array_logFC  \
gene
CPAR2_402940    3.624325e-15  2.704620e-18  0.116256     2.813060
CPAR2_603610    2.278684e-28  1.786128e-31  0.075113     3.381963
CPAR2_802240    1.270047e-39  1.317021e-42  0.032590     1.737264
CPAR2_100710    1.737989e-05  4.763157e-08  0.703526     3.071622
CPAR2_201490    3.710561e-09  6.393430e-12  0.621605     3.531186
CPAR2_405010    4.154604e-08  4.656723e-11  0.818460     2.719338
CPAR2_500850    2.441511e-14  2.082001e-17  0.572555     2.343294
CPAR2_401300    6.005738e-30  4.951225e-33  0.100559     1.944909
CPAR2_108000    3.669917e-25  2.710921e-28  0.132085     2.269046
CPAR2_109500    1.840644e-09  2.529278e-12  0.052639     1.157787
CPAR2_403180    3.607616e-03  1.971087e-05  0.343077     1.672911
CPAR2_203450    6.151374e-05  4.269486e-07  0.272336     2.501707
CPAR2_212210    1.163175e-07  1.950545e-10  0.160129     0.602846
CPAR2_302890    3.091300e-05  1.526660e-07  0.151055     1.403283
CPAR2_804750    2.685014e-04  1.310343e-06  2.474249     1.341796
CPAR2_503040    7.020749e-06  1.598696e-08  0.096727     0.341748
CPAR2_400770    9.463045e-05  3.614285e-07  0.081273     0.797369
CPAR2_600270    7.744523e-09  1.585619e-11  1.400509     1.607446
CPAR2_503690    1.818772e-06  3.824989e-09  1.556416     0.411362
CPAR2_800230    1.764126e-03  1.062719e-05  2.372344     0.275494
CPAR2_100100    1.390356e-13  2.412695e-16  0.089419     0.186909
CPAR2_205500    5.152817e-05  2.952641e-07  0.116548     0.279380
CPAR2_807040    3.438353e-07  4.504443e-10  0.038463    -0.141735
CPAR2_105270    3.091300e-05  1.715118e-07  0.104671     0.054419
CPAR2_807600    3.848694e-03  2.875500e-05  0.065452     0.085883
CPAR2_301390    3.558833e-04  2.049064e-06  0.402395    -0.081185

              array_FDR_standard  ...  score_abundance  score_array_effect  \
gene                              ...
CPAR2_402940            0.000058  ...         0.974598            0.992779
CPAR2_603610            0.000152  ...         0.971661            0.997408
CPAR2_802240            0.000041  ...         0.416969            0.978893
CPAR2_100710            0.000036  ...         0.396924            0.995186
CPAR2_201490            0.000007  ...         0.785208            0.997963
CPAR2_405010            0.000040  ...         0.980992            0.991668
CPAR2_500850            0.000302  ...         0.968550            0.987410
CPAR2_401300            0.000593  ...         0.875238            0.983336
CPAR2_108000            0.000914  ...         0.675825            0.986854
CPAR2_109500            0.000088  ...         0.648523            0.946862
CPAR2_403180            0.001926  ...         0.969069            0.977041
CPAR2_203450            0.000282  ...         0.927424            0.989446
CPAR2_212210            0.006590  ...         0.914809            0.801889
CPAR2_302890            0.001008  ...         0.531191            0.966858
CPAR2_804750            0.000136  ...         0.289960            0.963525
CPAR2_503040            0.011300  ...         0.854156            0.589335
CPAR2_400770            0.000722  ...         0.371004            0.879467
CPAR2_600270            0.000593  ...         0.235701            0.975005
CPAR2_503690            0.070428  ...         0.802661            0.661174
CPAR2_800230            0.037623  ...         0.717470            0.506758
CPAR2_100100            0.064653  ...         0.387247            0.364562
CPAR2_205500            0.048926  ...         0.271816            0.513423
CPAR2_807040            0.541291  ...         0.465526            0.284577
CPAR2_105270            0.666349  ...         0.585105            0.106647
CPAR2_807600            0.330212  ...         0.355625            0.171265
CPAR2_301390            0.436949  ...         0.289269            0.161822

              score_array_significance  score_platform_agreement  score_loo  \
gene
CPAR2_402940                  0.980744                  0.774671        1.0
CPAR2_603610                  0.969635                  0.715793        1.0
CPAR2_802240                  0.986299                  0.015553        1.0
CPAR2_100710                  0.988150                  0.733383        1.0
CPAR2_201490                  0.997038                  0.111091        1.0
CPAR2_405010                  0.986854                  0.547121        1.0
CPAR2_500850                  0.954268                  0.158859        1.0
CPAR2_401300                  0.932790                  0.026662        1.0
CPAR2_108000                  0.906128                  0.120348        1.0
CPAR2_109500                  0.977967                  0.030180        1.0
CPAR2_403180                  0.851324                  0.094982        1.0
CPAR2_203450                  0.955749                  0.002037        1.0
CPAR2_212210                  0.737826                  0.009072        1.0
CPAR2_302890                  0.900759                  0.051472        1.0
CPAR2_804750                  0.970931                  0.038326        1.0
CPAR2_503040                  0.679874                  0.007036        1.0
CPAR2_400770                  0.919830                  0.012405        1.0
CPAR2_600270                  0.932790                  0.011850        1.0
CPAR2_503690                  0.451768                  0.008332        1.0
CPAR2_800230                  0.534345                  0.007776        1.0
CPAR2_100100                  0.463062                  0.002777        1.0
CPAR2_205500                  0.499167                  0.006480        1.0
CPAR2_807040                  0.144047                  0.003333        1.0
CPAR2_105270                  0.097575                  0.004073        1.0
CPAR2_807600                  0.229032                  0.006851        1.0
CPAR2_301390                  0.185151                  0.005740        1.0

              score_edgeR  stat_score  P_top5_weights  P_top10_weights  \
gene
CPAR2_402940     0.998243    0.904434          0.0438           0.1072
CPAR2_603610     0.999122    0.902454          0.0210           0.0660
CPAR2_802240     1.000000    0.784969          0.0068           0.0246
CPAR2_100710     0.978746    0.797488          0.0028           0.0226
CPAR2_201490     0.994730    0.792013          0.0010           0.0034
CPAR2_405010     0.993325    0.871172          0.0000           0.0094
CPAR2_500850     0.996663    0.825499          0.0000           0.0000
CPAR2_401300     0.999473    0.820899          0.0000           0.0014
CPAR2_108000     0.999473    0.817697          0.0000           0.0024
CPAR2_109500     0.996663    0.780222          0.0000           0.0000
CPAR2_403180     0.944142    0.765029          0.0000           0.0000
CPAR2_203450     0.935359    0.752517          0.0000           0.0000
CPAR2_212210     0.990866    0.738282          0.0000           0.0000
CPAR2_302890     0.988231    0.735856          0.0000           0.0000
CPAR2_804750     0.975935    0.704705          0.0000           0.0000
CPAR2_503040     0.986650    0.695492          0.0000           0.0000
CPAR2_400770     0.974881    0.694351          0.0000           0.0000
CPAR2_600270     0.990163    0.693144          0.0000           0.0000
CPAR2_503690     0.989988    0.677473          0.0000           0.0000
CPAR2_800230     0.950992    0.640825          0.0000           0.0000
CPAR2_100100     0.996663    0.606555          0.0000           0.0000
CPAR2_205500     0.979448    0.596574          0.0000           0.0000
CPAR2_807040     0.991217    0.560852          0.0000           0.0000
CPAR2_105270     0.975935    0.540350          0.0000           0.0000
CPAR2_807600     0.949939    0.528316          0.0000           0.0000
CPAR2_301390     0.975233    0.524849          0.0000           0.0000

              combined_robustness
gene
CPAR2_402940             0.209284
CPAR2_603610             0.144914
CPAR2_802240             0.082462
CPAR2_100710             0.052915
CPAR2_201490             0.031623
CPAR2_405010             0.000000
CPAR2_500850             0.000000
CPAR2_401300             0.000000
CPAR2_108000             0.000000
CPAR2_109500             0.000000
CPAR2_403180             0.000000
CPAR2_203450             0.000000
CPAR2_212210             0.000000
CPAR2_302890             0.000000
CPAR2_804750             0.000000
CPAR2_503040             0.000000
CPAR2_400770             0.000000
CPAR2_600270             0.000000
CPAR2_503690             0.000000
CPAR2_800230             0.000000
CPAR2_100100             0.000000
CPAR2_205500             0.000000
CPAR2_807040             0.000000
CPAR2_105270             0.000000
CPAR2_807600             0.000000
CPAR2_301390             0.000000

[26 rows x 50 columns]

In [77]:
normoxia_data.head()

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
CapafMp06.4,9.942816,-3.955360,1.095701,-3.609889,3.063285e-04,1.548780e-03
CPAR2_213800,40.044971,-3.881981,0.917280,-4.232056,2.315644e-05,1.695403e-04
CPAR2_703250,360.215745,-2.742302,0.256202,-10.703657,9.783921e-27,2.021079e-24
CPAR2_402370,11.313434,-4.890895,1.314170,-3.721659,1.979179e-04,1.074889e-03
CPAR2_406090,8.933948,-3.048406,0.912154,-3.341987,8.318103e-04,3.569133e-03

In [78]:
hypoxia_data.head()

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
CPAR2_701390,810.022634,2.268745,0.464502,4.884255,1.038206e-06,1.091815e-05
CPAR2_205290,148.412553,2.245343,0.480186,4.675984,2.925475e-06,2.746907e-05
CPAR2_600270,218.271357,3.636161,0.402685,9.029797,1.719901e-19,1.776412e-17
CPAR2_205500,250.903803,2.815860,0.369206,7.626796,2.406605e-14,1.364687e-12
CPAR2_100710,385.891356,3.041893,0.394597,7.708852,1.269543e-14,7.729515e-13

In [ ]:
print(len(hypoxia_data.query(hypoxia_query).index))
print(hypoxia_data.query(hypoxia_query))

27
                  baseMean  log2FoldChange     lfcSE       stat        pvalue  \
CPAR2_600270    218.271357        3.636161  0.402685   9.029797  1.719901e-19
CPAR2_205500    250.903803        2.815860  0.369206   7.626796  2.406605e-14
CPAR2_100710    385.891356        3.041893  0.394597   7.708852  1.269543e-14
CPAR2_109500    800.730446        2.527252  0.225288  11.217853  3.332634e-29
CPAR2_401300   2098.278340        3.385799  0.199031  17.011411  6.759038e-65
CPAR2_503040   1851.914845        2.763682  0.328954   8.401420  4.411107e-17
CPAR2_503690   1418.046930        2.702861  0.302573   8.932918  4.149172e-19
CPAR2_402940   7717.697743        2.953719  0.227468  12.985234  1.483837e-38
CPAR2_404850  33479.580383        6.236384  0.693835   8.988280  2.511301e-19
CPAR2_302890    567.068475        2.512928  0.299746   8.383538  5.136022e-17
CPAR2_400770    355.303773        2.795682  0.375196   7.451254  9.245738e-14
CPAR2_108000    870.276156        2.999223  0.182172  16.463683  6.690333e-61
CPAR2_100100    375.406737        3.272074  0.279941  11.688442  1.460413e-31
CPAR2_405010   9437.133347        2.526733  0.243220  10.388677  2.791987e-25
CPAR2_201490   1319.671380        2.852736  0.277791  10.269367  9.683770e-25
CPAR2_804750    268.603407        2.620833  0.355712   7.367842  1.734120e-13
CPAR2_301390    267.815009        2.580036  0.352782   7.313408  2.604500e-13
CPAR2_603610   7156.497733        3.539613  0.218040  16.233781  2.909708e-59
CPAR2_800230   1007.442908        2.682579  0.412452   6.503983  7.822060e-11
CPAR2_203450   3371.879372        6.099712  1.045130   5.836317  5.336728e-09
CPAR2_807600    336.574079        2.603498  0.414091   6.287267  3.231025e-10
CPAR2_403180   6939.334408        2.578102  0.404939   6.366638  1.932161e-10
CPAR2_500850   6775.786781        3.000223  0.239512  12.526420  5.352491e-36
CPAR2_802240    408.763107        3.522685  0.183325  19.215504  2.745569e-82
CPAR2_212210   2921.963451        2.838374  0.301261   9.421647  4.440660e-21
CPAR2_105270    658.202531        2.915186  0.379652   7.678580  1.608620e-14
CPAR2_807040    468.906335        2.887650  0.318834   9.056901  1.342091e-19

                      padj
CPAR2_600270  1.776412e-17
CPAR2_205500  1.364687e-12
CPAR2_100710  7.729515e-13
CPAR2_109500  9.637977e-27
CPAR2_401300  7.818855e-62
CPAR2_503040  3.644835e-15
CPAR2_503690  4.067595e-17
CPAR2_402940  6.601935e-36
CPAR2_404850  2.548309e-17
CPAR2_302890  4.184049e-15
CPAR2_400770  4.531978e-12
CPAR2_108000  6.449481e-58
CPAR2_100100  4.692794e-29
CPAR2_405010  5.046516e-23
CPAR2_201490  1.600312e-22
CPAR2_804750  7.836053e-12
CPAR2_301390  1.124211e-11
CPAR2_603610  2.404250e-56
CPAR2_800230  2.028289e-09
CPAR2_203450  9.676374e-08
CPAR2_807600  7.445517e-09
CPAR2_403180  4.695638e-09
CPAR2_500850  2.063921e-33
CPAR2_802240  5.293457e-79
CPAR2_212210  5.707728e-19
CPAR2_105270  9.592020e-13
CPAR2_807040  1.411391e-17

In [19]:
print(normoxia_data.query(normoxia_query).index)
print(normoxia_data.query(normoxia_query))

Index(['CPAR2_703250', 'CPAR2_600600', 'CPAR2_213050', 'CPAR2_700940',
       'CapafMp03', 'CPAR2_600590'],
      dtype='object')
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
CPAR2_703250   360.215745       -2.742302  0.256202 -10.703657  9.783921e-27
CPAR2_600600   389.960141       -2.596029  0.366291  -7.087349  1.367058e-12
CPAR2_213050  1407.414916       -3.208022  0.321823  -9.968269  2.098550e-23
CPAR2_700940  2721.593982       -2.518067  0.305699  -8.237086  1.764557e-16
CapafMp03      238.620636       -2.993943  0.543321  -5.510449  3.579200e-08
CPAR2_600590   310.026809       -3.051175  0.433290  -7.041870  1.896763e-12

                      padj
CPAR2_703250  2.021079e-24
CPAR2_600600  5.036347e-11
CPAR2_213050  3.371670e-21
CPAR2_700940  1.342921e-14
CapafMp03     5.462294e-07
CPAR2_600590  6.772145e-11

List of retained gene from the filter pipeline:

CPAR2_600270
CPAR2_205500
CPAR2_100710
CPAR2_109500
CPAR2_401300
CPAR2_503040
CPAR2_503690
CPAR2_402940
CPAR2_404850
CPAR2_302890
CPAR2_400770
CPAR2_108000
CPAR2_100100
CPAR2_405010
CPAR2_201490
CPAR2_804750
CPAR2_301390
CPAR2_603610
CPAR2_800230
CPAR2_203450
CPAR2_807600
CPAR2_403180
CPAR2_500850
CPAR2_802240
CPAR2_212210
CPAR2_105270
CPAR2_807040
CPAR2_703250
CPAR2_600600
CPAR2_213050
CPAR2_700940
CapafMp03
CPAR2_600590